# Generated by Django 3.1.4 on 2021-01-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee_Aca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_deb', models.DateField()),
                ('annee_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('date_naiss', models.DateField()),
                ('sexe', models.CharField(max_length=8)),
                ('nationalite', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('moyenne', models.FloatField()),
                ('date_licence', models.DateField()),
                ('date_obt_licence', models.DateField()),
                ('date_M1', models.DateField()),
                ('date_M2', models.DateField(null=True)),
                ('date_obt_M1', models.DateField()),
                ('date_obt_M2', models.DateField(null=True)),
                ('matricule', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_stn', models.DateField(null=True)),
                ('type_stn', models.CharField(max_length=30)),
                ('note', models.IntegerField()),
                ('mention', models.CharField(max_length=20)),
                ('num_comm', models.CharField(max_length=20)),
                ('etudiants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enregistrement.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president', models.CharField(max_length=100)),
                ('rapporteur_1', models.CharField(max_length=100)),
                ('rapporteur_2', models.CharField(max_length=100, null=True)),
                ('encadreur_1', models.CharField(max_length=100)),
                ('encadreur_2', models.CharField(max_length=100, null=True)),
                ('encadreur_3', models.CharField(max_length=100, null=True)),
                ('enseignants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enregistrement.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Encadrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_heures', models.IntegerField()),
                ('sujet', models.TextField()),
                ('enseignants', models.ManyToManyField(to='enregistrement.Enseignant')),
                ('etudiants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enregistrement.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dep', models.CharField(max_length=50)),
                ('parcours', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=30)),
                ('annee_aca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enregistrement.annee_aca')),
                ('etudiants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enregistrement.etudiant')),
            ],
        ),
    ]
