# Generated by Django 3.1.4 on 2021-01-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enregistrement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annee_aca',
            name='annee_deb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='annee_aca',
            name='annee_fin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_M1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_M2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_licence',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_obt_M1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_obt_M2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_obt_licence',
            field=models.IntegerField(),
        ),
    ]
