# Generated by Django 3.1.4 on 2021-01-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enregistrement', '0002_auto_20210126_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_M2',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_obt_M2',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
