# Generated by Django 3.1.4 on 2021-01-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enregistrement', '0003_auto_20210126_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_M2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_obt_M2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(choices=[('MASCULIN', 'MASCULIN'), ('FEMININ', 'FEMININ'), ('AUTRES', 'AUTRES')], default='AUTRES', max_length=25),
        ),
    ]
