# Generated by Django 3.1.4 on 2021-01-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enregistrement', '0005_auto_20210128_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enregistrement.grade'),
        ),
    ]
