# Generated by Django 3.1.5 on 2021-01-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enregistrement', '0006_auto_20210128_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='jury',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enregistrement.jury'),
            preserve_default=False,
        ),
    ]
