# Generated by Django 3.1.5 on 2021-01-30 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enregistrement', '0009_auto_20210130_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_departement', models.CharField(max_length=50)),
                ('abr_departement', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_niveau', models.CharField(max_length=10)),
                ('annee_aca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enregistrement.annee_aca')),
            ],
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_parcours', models.CharField(max_length=50)),
                ('abr_parcours', models.CharField(max_length=8)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enregistrement.departement')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enregistrement.niveau')),
            ],
        ),
        migrations.AlterField(
            model_name='encadrement',
            name='etudiants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encadrements', to='enregistrement.etudiant'),
        ),
        migrations.DeleteModel(
            name='Cursus',
        ),
    ]
