# Generated by Django 3.1.5 on 2021-01-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enregistrement', '0010_auto_20210130_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcours',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='parcours',
            name='niveau',
        ),
        migrations.AddField(
            model_name='niveau',
            name='parcours',
            field=models.ManyToManyField(to='enregistrement.Parcours'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='annee_aca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveau', to='enregistrement.annee_aca'),
        ),
    ]
