# Generated by Django 3.1.5 on 2021-01-30 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enregistrement', '0012_parcours_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annee_aca',
            name='annee_deb',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2021)]),
        ),
        migrations.AlterField(
            model_name='annee_aca',
            name='annee_fin',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1991), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
