# Generated by Django 3.1.5 on 2021-01-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enregistrement', '0013_auto_20210130_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='lib_departement',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='lib_niveau',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='lib_parcours',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
