# Generated by Django 3.1.5 on 2021-01-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enregistrement', '0015_auto_20210130_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='date_M1',
            new_name='date_deb_M1',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='date_M2',
            new_name='date_deb_M2',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='date_licence',
            new_name='date_deb_licence',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='moyenne',
            new_name='moyenne_licence',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='moyenne_master1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='abr_grade',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='grade',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
